### PR TITLE
Implemented Fw update over FoE

### PR DESCRIPTION
**Pull request by XzuluX**
Implemented firmware update for slave device.

Enhanced wrapper with functionality to set mailbox configuration for specific slave in order to download firmware file over FoE. Firmware update functionality has been verified with Beckoff Slave EL3021.  
Implemented also functions to trigger slave state transition to new state and read current slave state.

### CODE REVIEW

**Comment by Apollo3zehn** [comment]
Thanks for that useful PR. However, could you please raise it against the dev branch? Thanks :)

**Comment by XzuluX** [comment]
I rebased it to dev branch, so it's on the top of dev. Do you mean that with raise against dev?

**Comment by Apollo3zehn** [comment]
No, sorry I mean this 
grafik

You want to merge into master, but I would prefer if you could change it to dev. Thank you!

**Review by Apollo3zehn — CHANGES_REQUESTED** [review]
Thanks again, looks very good. There is only one thing I think should be changed: You have renamed `RequestOpState` to `RequestCommonState`. But `RequestOpState` is specific to the OP state because it contains 
```
ecx_send_processdata(context);
ecx_receive_processdata(context, EC_TIMEOUTRET);
```

I think we could instead rename the `CheckSafeOpState` method which does exactly what I think you indent with `RequestCommonState` and let `RequestOpState` untouched.

**Comment by Apollo3zehn** [comment]
Sorry, I was wrong, `CheckSafeOpState` is really just a check. Maybe we can instead change the code of `RequestCommonState` to skip the processdata methods for states other than "OP".

**Comment by XzuluX** [comment]
Thank's for reviewing my PR! I changed RequestCommonState and now the processdata methods are only performed if current state is OP.

**Pull request merged**
